package com.tigernum.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (Tiger Orange palette)
val PrimaryLight = Color(0xFFC75B00)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDBC9)
val OnPrimaryContainerLight = Color(0xFF441A00)
val SecondaryLight = Color(0xFF72573F)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFDDBC1)
val OnSecondaryContainerLight = Color(0xFF281603)
val TertiaryLight = Color(0xFF59633E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFDDE8BA)
val OnTertiaryContainerLight = Color(0xFF161F01)
val ErrorLight = Color(0xFFBA1A1A)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorLight = Color(0xFFFFFFFF)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFFF8F4)
val OnBackgroundLight = Color(0xFF201A13)
val SurfaceLight = Color(0xFFFFF8F4)
val OnSurfaceLight = Color(0xFF201A13)
val SurfaceVariantLight = Color(0xFFF1DFD1)
val OnSurfaceVariantLight = Color(0xFF50443A)
val OutlineLight = Color(0xFF827367)
val InverseSurfaceLight = Color(0xFF352F28)
val InverseOnSurfaceLight = Color(0xFFFAEFE7)
val InversePrimaryLight = Color(0xFFFFB77B)

// Dark Theme Colors
val PrimaryDark = Color(0xFFFFB77B)
val OnPrimaryDark = Color(0xFF6A2E00)
val PrimaryContainerDark = Color(0xFF984500)
val OnPrimaryContainerDark = Color(0xFFFFDBC9)
val SecondaryDark = Color(0xFFE1BFA6)
val OnSecondaryDark = Color(0xFF402914)
val SecondaryContainerDark = Color(0xFF583F29)
val OnSecondaryContainerDark = Color(0xFFFDDBC1)
val TertiaryDark = Color(0xFFC1CC9F)
val OnTertiaryDark = Color(0xFF2B3412)
val TertiaryContainerDark = Color(0xFF414A27)
val OnTertiaryContainerDark = Color(0xFFDDE8BA)
val ErrorDark = Color(0xFFFFB4AB)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorDark = Color(0xFF690005)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF17120D)
val OnBackgroundDark = Color(0xFFEBE0D8)
val SurfaceDark = Color(0xFF17120D)
val OnSurfaceDark = Color(0xFFEBE0D8)
val SurfaceVariantDark = Color(0xFF50443A)
val OnSurfaceVariantDark = Color(0xFFD4C3B5)
val OutlineDark = Color(0xFF9D8D7F)
val InverseSurfaceDark = Color(0xFFEBE0D8)
val InverseOnSurfaceDark = Color(0xFF201A13)
val InversePrimaryDark = Color(0xFFC75B00)
